import styles from '@s/projects/txttogit/main.module.scss';
import text_styles from '@s/text/main.module.scss';
import basic_layout_styles from '@s/projects/basic_layout.module.scss';

import Preview from '@p/projectsTxtToGit.png';
import Demo1 from '@p/projectsTxtToGitDemo1.png';
import Demo2 from '@p/projectsTxtToGitDemo2.png';

import Link from 'next/link';
import Image from 'next/image';

const TxtToGit = () => {
  return (
    <>
      <div className={basic_layout_styles.wrapper}>
        <div className={basic_layout_styles.main}>
          <div className={basic_layout_styles.top_wrapper}>
            <h1 className={text_styles.title}>Text to git</h1>
            <div className={basic_layout_styles.top_information}>
              View source code{' '}
              <Link
                href='https://github.com/mzoesch/TxtToGit'
                target='_blank'
                className={text_styles.link}
              >
                here
              </Link>
              .
            </div>
          </div>
          <div className={text_styles.text}>
            <div className={text_styles.paragraph}>
              Allows you to write all ASCII characters from 0x20 to 0x7E to your
              GitHub profile page by committing on specific dates in a year. You
              can then see your text on your profile pages contributions list.
            </div>
            <h2 className={text_styles.subtitle} style={{ marginTop: '5rem' }}>
              How to use (generated by argparse)
            </h2>
            <h3
              className={text_styles.subtitle}
              style={{ marginTop: '2.25rem' }}
            >
              usage:
            </h3>
            <div className={text_styles.paragraph}>
              <div>app.py</div>
              <div>
                [-h] [-c CLEAN] [-y YEAR] [--firstDayOfWeek FIRSTDAYOFWEEK] [-m
                USEMONOSPACE] [-s DEFAULTSPACE] [-a ALIGN] [-msg MESSAGE]
                [-msgStr MESSAGESTRING] [-cAE CLEANAFTEREXECUTION] [-min
                MINNUMBEROFCOMMITSATONEDAY] [-max MAXNUMBEROFCOMMITSATONEDAY]
                [-mCDR MAKECOMMITSINDIFFERENTREPO] [-nDR NAMEOFDIFFERENTREPO]
                [-iER IGNOREEXISTINGGITREPO]{' '}
              </div>
            </div>
            <h3
              className={text_styles.subtitle}
              style={{ marginTop: '2.25rem' }}
            >
              optional arguments:
            </h3>
            <div className={text_styles.paragraph}>
              <div>-h, --help show this help message and exit</div>
              <div>-c CLEAN, --clean CLEAN Clean build dirs (def.: 0). </div>
              <div>
                -y YEAR, --year YEAR Year to gen for (def.: current year).
              </div>
              <div>
                --firstDayOfWeek FIRSTDAYOFWEEK First day of week (So.: 0, Mo.:
                1, ...) (def.: 0).
              </div>
              <div>
                -m USEMONOSPACE, --useMonospace USEMONOSPACE Use monospace
                (def.: 1).
              </div>
              <div>
                -s DEFAULTSPACE, --defaultSpace DEFAULTSPACE Default space in
                weeks (def.: 1).
              </div>
              <div>
                -a ALIGN, --align ALIGN Align text (0: left, 1: center, 2:
                right) (def.: 0).
              </div>
              <div>
                -msg MESSAGE, --message MESSAGE Message in commits (e.g.
                &quot;Char SpaceInWeeks, A2, b1, ...&quot;) (def.: empty).
              </div>
              <div>
                -msgStr MESSAGESTRING, --messageString MESSAGESTRING Message in
                commits; uses default Space for all characters (e.g.
                &quot;ab&quot;) (def.: empty).
              </div>
              <div>
                -cAE CLEANAFTEREXECUTION, --cleanAfterExecution
                CLEANAFTEREXECUTION Clean build dirs after execution (def.: 1).
              </div>
              <div>
                -min MINNUMBEROFCOMMITSATONEDAY, --minNumberOfCommitsAtOneDay
                MINNUMBEROFCOMMITSATONEDAY Min number of commits at one day that
                is commitable (def.: 1).
              </div>
              <div>
                -max MAXNUMBEROFCOMMITSATONEDAY, --maxNumberOfCommitsAtOneDay
                MAXNUMBEROFCOMMITSATONEDAY Max number of commits at one day that
                is commitable (def.: 5).
              </div>
              <div>
                -mCDR MAKECOMMITSINDIFFERENTREPO, --makeCommitsInDifferentRepo
                MAKECOMMITSINDIFFERENTREPO Make commits in different repo (def.:
                1).
              </div>
              <div>
                -nDR NAMEOFDIFFERENTREPO, --nameOfDifferentRepo
                NAMEOFDIFFERENTREPO Name of different repo (def.:
                myTextOnGitHub).
              </div>
              <div>
                -iER IGNOREEXISTINGGITREPO, --ignoreExistingGitRepo
                IGNOREEXISTINGGITREPO Ignore existing git repo (def.: 0).
              </div>
            </div>
          </div>
          <div>
            <h2 className={text_styles.subtitle} style={{ marginTop: '5rem' }}>
              Preview - link to demo{' '}
              <Link
                href='https://github.com/mzoesch?tab=overview&from=2019-12-01&to=2019-12-31'
                target='_blank'
                className={text_styles.link}
              >
                here
              </Link>
            </h2>
            <div>
              <h3
                className={text_styles.subtitle}
                style={{ marginTop: '0rem' }}
              >
                Command used
              </h3>
              <div className={styles.code_example}>
                <span style={{ color: 'lightgreen' }}>python</span>{' '}
                <span style={{ textDecoration: 'underline' }}>app.py</span> -y
                2019 -msgStr{' '}
                <span style={{ color: 'yellow' }}>&quot;@MZOESCH&quot;</span> -a
                1
              </div>
              <br />
              <br />
              <br />
              <Image
                src={Preview}
                alt='Preview of the project'
                style={{ width: '100%', height: '100%' }}
              />
            </div>

            <div style={{ marginTop: '2rem' }}>
              <h2 className={text_styles.subtitle}>Example output</h2>
              <Image
                src={Demo1}
                alt='Preview of the project'
                style={{ width: '100%', height: '100%' }}
              />
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  height: '2rem',
                  marginBottom: '0.75rem',
                }}
              >
                . . .
              </div>
              <Image
                src={Demo2}
                alt='Preview of the project'
                style={{ width: '100%', height: '100%', marginBottom: '5rem' }}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TxtToGit;
